---
- name: Install monit
  ansible.builtin.package:
    name: monit

- name: Copy monit default configuration
  ansible.builtin.copy:
    src: monitrc
    dest: "{{ etc_prefix }}/etc/monitrc"
    mode: "0600"
  when: ansible_os_family == "FreeBSD"

- name: Create {{ etc_prefix }}/etc/monit/conf.d/ # noqa: name[template]
  ansible.builtin.file:
    path: "{{ etc_prefix }}/etc/monit/conf.d/"
    state: directory
    mode: "0755"
  when: monit_configs is defined or monit_services is defined

- name: Copy monit configurations to {{ etc_prefix }}/etc/monit/conf.d/ # noqa: name[template]
  ansible.builtin.template:
    src: monit/{{ item }}
    dest: "{{ etc_prefix }}/etc/monit/conf.d/"
    mode: "0644"
  notify: Reload monit
  loop: "{{ monit_configs }}"
  when: monit_configs is defined

- name: Copy monit service to {{ etc_prefix }}/etc/monit/conf.d/{{ service }} # noqa: name[template]
  ansible.builtin.template:
    src: monit/local-mit-service
    dest: "{{ etc_prefix }}/etc/monit/conf.d/local-mit-{{ service }}"
    mode: "0644"
  notify: Reload monit
  loop: "{{ monit_services }}"
  loop_control:
    loop_var: service
  when: monit_services is defined

- name: Include inventory_hostname.yml
  ansible.builtin.include_tasks: "{{ tasks_file }}"
  when: tasks_file != ""
  vars:
    tasks_file: "{{ lookup('ansible.builtin.first_found', files, errors='ignore') }}"
    files:
      - "local/roles/{{ ansible_role_name }}/tasks/{{ inventory_hostname }}.yml"

- name: Enable and start monit
  ansible.builtin.service:
    name: monit
    state: started
    enabled: true
