---

- name: Install monit
  package: 
    name: monit

- name: Copy monit configuration
  template:
    src: "monit/{{ item }}"
    dest: /etc/monit/conf.d/
  notify: Reload monit
  loop: "{{ monit_configs }}"
  when: monit_configs is defined

