---

# On buster only available via backports, add
# deb http://deb.debian.org/debian buster-backports main
- name: Install monit
  apt: 
    pkg: monit
- name: Copy monit configuration
  template:
    src: local-mit-zabbix
    dest: /etc/monit/conf.d/
  notify: Reload monit

